### PR TITLE
Regex search

### PR DESCRIPTION
**Pull request by gskerry**
image

### CODE REVIEW

**Comment by itsaliu90** [comment]
Sweet feature, can we clean up the UI a bit though?

**Comment by gskerry** [comment]
Just pushed a slight improvement. At this stage will probably just be shooting for passable 
:8ball:

**Comment by gskerry** [comment]
little better.

**Comment by gskerry** [comment]
Resolved to master. Good to go.

**Comment by itsaliu90** [comment]
super sick, feels like a present :santa:

**Pull request merged**
