### PR TITLE
Film factory

### PR DESCRIPTION
**Pull request by gskerry**
Films route up. 
Currently display full catalog: 
image

Teeing up for / Next: 
- build out 'summary-view' for each movie 
- refactor route to be take search params (e.g. drop down list of categories; dynamic filter).

### CODE REVIEW

**Comment by itsaliu90** [comment]
Very cool, but this PR seems to conflict with @darksim735 's https://github.com/carolynyoo/stack_store/pull/42. Let's resolve tomorrow and we maybe should also be more clear about claiming Issues so we don't duplicate work/create merge conflicts.

**Comment by gskerry** [comment]
#42 is for individual product detail (vs. browser view here) so the state and routes are different ( @carolynyoo and I discussed a bit), but there will be some merge/clean up on the views etc once we get things set up. Agree still good idea to powow to make sure issues are detailed enough to be avoid overlap as much as possible.

**Comment by itsaliu90** [comment]
Ahh makes sense, cool! :hamburger:

**Comment by itsaliu90** [comment]
Ahh you're right, makes sense. Cool! :hamburger:

On Wed, Apr 22, 2015 at 11:53 PM, gskerry notifications@github.com wrote:

> #42 https://github.com/carolynyoo/stack_store/pull/42 is for individual
> product detail (vs. browser view here) so the state and routes are
> different ( @carolynyoo https://github.com/carolynyoo and I discussed a
> bit), but there will be some merge/clean up on the views etc once we get
> things set up. Agree still good idea to powow to make sure issues are
> detailed enough to be avoid overlap as much as possible.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/carolynyoo/stack_store/pull/46#issuecomment-95418270.

## 

Alex Liu
_Account Manager_

Cipher_Health_ http://www.cipherhealth.com/ | @cipherhealth
https://twitter.com/cipherhealth

555 8th Avenue, Suite 701
New York, NY 10018
(585) 662-9096 | aliu@cipherhealth.com

_The information contained in this email message is intended only for use
of the individual or entity named above. If the reader of this message is
not the intended recipient, or the employee or agent responsible to deliver
it to the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this communication in error, please
immediately notify me by email (aliu@cipherhealth.com
aliu@cipherhealth.com) and destroy the original message. Thank you._

**Comment by carolynyoo** [comment]
are we ready to merge this? i ok it

**Pull request merged**
